machine:
  services:
    - docker

dependencies:
  override:
    - docker info
    - docker version

    - cp test/Dockerfile-ubuntu14.04 Dockerfile
    - docker build  -t nodejs_trusty   .

    - cp test/Dockerfile-ubuntu12.04 Dockerfile
    - docker build  -t nodejs_precise  .

    - cp test/Dockerfile-debian8 Dockerfile
    - docker build  -t nodejs_jessie   .

    - cp test/Dockerfile-debian7 Dockerfile
    - docker build  -t nodejs_wheezy   .

    - cp test/Dockerfile-centos7 Dockerfile
    - docker build  -t nodejs_centos7  .

    - cp test/Dockerfile-centos6 Dockerfile
    - docker build  -t nodejs_centos6  .

test:
  override:
    - docker run -i nodejs_trusty   > result-ubuntu14.04
    - docker run -i nodejs_precise  > result-ubuntu12.04
    - docker run -i nodejs_jessie   > result-debian8
    - docker run -i nodejs_wheezy   > result-debian7
    - docker run -i nodejs_centos7  > result-centos7
    - docker run -i nodejs_centos6  > result-centos6

    - echo "==> Validating the test results..."
    - sh -c "[ -s result-ubuntu14.04 ]"
    - sh -c "[ -s result-ubuntu12.04 ]"
    - sh -c "[ -s result-debian8     ]"
    - sh -c "[ -s result-debian7     ]"
    - sh -c "[ -s result-centos7     ]"
    - sh -c "[ -s result-centos6     ]"
