#!/usr/bin/env php
<?php
require_once __DIR__.'/vendor/autoload.php';

use Cmd\MigrateCommand;
use Cmd\ConfigCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new MigrateCommand);
$application->add(new ConfigCommand);
$application->run();
