- name: ensure database is created
  mysql_db: login_user={{ mysql_user }} login_password={{ mysql_pw }} name={{ dbname }} state=present

- name: ensure user has access to database
  mysql_user: login_user={{ mysql_user }} login_password={{ mysql_pw }} name={{ dbuser }} password={{ dbpassword }} priv={{ dbname }}.*:ALL state=present