@extends ('layouts.default')

@section('title')
    Nosacījumi un noteikumi
@stop

@section('content')
<div style="margin: 30px auto;">

<h1 class="heading text-center">Nosacījumi un noteikumi</h1>

<p>Šie nosacījumi un noteikumi var tikt atjaunoti ik pa laikam, un tie attiecas uz mūsu pakalpojumiem, kas tieši vai netieši (caur izplatītājiem) ir pieejami tiešsaistē caur mobilo ierīci, e-pastu vai telefonu. Ja piekļūstat, pārskatāt vai izmantojat mūsu mājas lapu vai tās aplikācijas caur jebkādu platformu (kas kopumā tiek saukta par "mājas lapu") un/vai veicot rezervējumu, Jūs apstipriniet, kas esat piekritis, izlasījis un sapratis nosacījumus un noteikumus, kas norādīti zemāk (tostarp Privātuma deklarāciju).</p>

<p>Šīs lapas, saturs un infrastruktūra, kā arī tiešsaistes skaistumkopšanas rezervējumu pakalpojumi, kas nodrošināti šajās lapās caur mājas lapu ("pakalpojumi") pieder, tos pārvalda un nodrošina tobook.lv, tupmāk tekstā  "mums", "mēs" vai "mūsu". Mājas lapa tiek nodrošināta jūsu privātai, nekomerciālai izmantošanai, kā arī saskaņā ar zemāk norādītajiem nosacījumiem un noteikumiem.</p>

<h3 class="heading">1. Mūsu pakalpojumu klāsts</h3>
<p>Ar mūsu mājas lapas palīdzību mēs (tobook.lv  un tās saistītie (izplatītāju) partneri)) nodrošinām tiešsaistes platformu, kurā visa veida skaistumkopšanas tirgus dalībnieki (piemēram, frizētavas, solāriji, spa, masāžas kabineti un manikīra studijas, kopā sauktas par saloniem) var reklamēt savus pakalpojumus  rezervējumiem, un kurā mājas lapas apmeklētāji var veikt šādus rezervējumus. Kad veicat rezervējumu, izmantojot tobook.lv, jūs kļūstat par (juridiski saistošu) līgumattiecību dalībnieku ar attiecīgi rezervētās salona administrāciju. No brīža, kad veicat rezervējumu, mēs darbojamies kā starpnieks starp salonu un jums, nododot rezervējuma informāciju atbilstošajam salonam un nosūtot jums apstiprinājuma e-pastu salona vārdā.</p>

<p>Kad mēs formulējam mūsu pakalpojumus, informāciju, kuru mēs norādām, mums ir iesniedzis salons. Piemēram, salona administrācijai ir piešķirta pieeja Iekštīklam, kur tā ir pilnībā atbildīga par cenām, pieejamību un citu mājas lapā pieejamo informāciju. Lai arī mēs praktizējam un rūpējamies par mūsu pakalpojumiem, mēs nevaram garantēt, ka visa informācija ir akurāta, pilnīga vai pareiza, kā arī mēs nevaram būt atbildīgi par kļūdām (tostarp pakalpojumu un drukas kļūdām), jebkādiem pārtraukumiem (mūs mājas lapas īslaicīgiem un/vai daļējiem traucējumiem, labošanu, atjaunināšanu vai uzlabošanu), neakurātu, maldinošu vai nepatiesu informāciju vai informācijas trūkumu. Katrs salons ir atbildīgs par (aprakstošās) informācijas atbilstību patiesībai, pilnīgumu un precizitāti (tostarp cenām un pieejamību), kas publicēta mūsu mājas lapā. Mūsu mājas lapa nesastāda šo informāciju, tādēļ tā nevar tikt izmantota kā atsauce vai pierādījums salona kvalitātei.</p>

<p>Mūsu pakalpojumi ir pieejami privātai un nekomerciālai izmantošanai. Tādēļ jūs nedrīkstat pārdot, izveidot hiperlinkus, izmantot, kopēt, kontrolēt (spider, scrape), attēlot, lejuplādēt vai pārstrādāt saturu, informāciju, programmatūru, produktus vai pakalpojumus, kas pieejami mūsu mājas lapā jebkādai komerciālai vai konkurējošai aktivitātei vai mērķim.</p>

<h3 class="heading">2. Cenas garantija</h3>
<p>Visas tobook.lv norādītās cenas ir par vienu pakalpojumu ar PVN un visiem citiem nodokļiem (nodokļi var mainīties atbilstoši normatīvo aktu prasībām), ja vien nav norādīts citādi mājas lapā vai apstiprinājuma e-pastā.</p>

<p>Dažreiz lētāki piedāvājumi ir pieejami mūsu mājas lapā uz konkrētiem laikiem, tomēr šīs cenas ir norādījušas saloni  un tām var tikt piemēroti īpaši ierobežojumi un noteikumi, piemēram, saistībā ar atcelšanas noteikumiem un depozīta iemaksu. Lūdzu, pārbaudiet pakalpojuma un cenas informāciju rūpīgi par šiem noteikumiem, pirms veicat rezervējumu.</p>

<p>Nepārprotamas kļūdas (tostarp drukas kļūdas) nav saistošas.</p>

<p>Visi īpašie piedāvājumi un akcijas ir atbilstoši atzīmēti.</p>

<h3 class="heading">3. Privātums un sīkdatnes</h3>
Tobook.lv  respektē jūsu privātumu. Lūdzu, pārlasiet mūsu Privātuma un sīkdatņu deklarāciju plašākai informācijai.

<h3 class="heading">4. Bez maksas</h3>
Mūsu pakalpojumi ir bez maksas, jo atšķirībā no citiem dažiem pakalpojumu sniedzējiem mēs no jums neiekasēsim pakalpojuma maksu un nepievienosim papildu (rezervējuma) maksas pakalpojuma cenai.

<h3 class="heading">5. Kredītkarte vai bankas pārskaitījums</h3>
<p>Ja ir pieejama un piemērota iespēja, tad salons klientiem piedāvā iespēju maksāt par rezervējumiem (daļēji vai pilnībā un saskaņā ar salona apmaksas noteikumiem) tieši salonam rezervējuma veikšanas laikā ar drošu tiešsaistes maksājumu (to nodrošina un atbalsta lietotāja banka). Maksājums drošā veidā tiek veikts no jūsu kredītkartes / debetkartes vai no jūsu bankas konta uz mūsu konta un pēc tam tiek pārskaitīts uz salona bankas kontu, izmantojot trešās puses maksājuma apstrādātāju.</p>

<p>Lūdzu, ņemiet vērā, ka par noteiktām (neatmaksājamām) cenām un īpašajiem piedāvājumiem salona administrācija, iespējams, var pieprasīt iepriekšēju bankas pārskaitījumu vai kredītkartes maksājumu (ja pieejams), tādēļ jūsu kredītkarte var tikt priekšautorizēta vai no tās var tikt ieturēts maksājums (dažreiz bez iespējas to atmaksāt) rezervējuma veikšanas laikā. Lūdzu, pirms veicat rezervējumu, rūpīgi pārbaudiet pakalpojuma informāciju par šādiem noteikumiem.</p>

<p>Visas karšu transakcijas tiek izpildītas, izmantojot 3D Secure sistēmu. Tas nozīmē, ka:</p>
<ol>
    <li>ja kartei ir aktivizēta 3DS funkcija, pēc karšu datu ievades pircējs tiek pāradresēts uz savas bankas (izdevējbankas) lapu, kur maksājums papildus jāapstiprina ar paroli. </li>
    <li>ja kartei nav aktivizēta 3DS funkcija un izdevējbanka to nepieprasa, maksājums tiek pabeigts uzreiz pēc karšu datu ievades.</li>
    <li>ja kartei nav aktivizēta 3DS funkcija, bet izdevējbanka ir noteikusi, ka tā ir obligāta, maksājums tiks noraidīts.</li>
</ol>

<p>Jebkurā gadījumā, ja kartes dati tiek izmantoti bez kartes īpašnieka ziņas (nozaudēta karte, nelikumīgi iegūti karšu dati u.t.t.), visa atbildība gulstas uz pašu kartes īpašnieku, jo maksājums ir veikts caur 3DS sistēmu.</p>

<h3 class="heading">6. Atcelšana</h3>
<p>Kad veicat salona pakalpojuma rezervējumu, jūs piekrītat un apstiprināt atbilstošos atcelšanas un neierašanās gadījumu noteikumus, kā arī jebkurus citus (pakalpojuma) noteikumus un nosacījumus, kas ir saistoši jūsu rezervējumam vai uzturēšanās periodam, tostarp tos, kas saistīti ar nodrošinātajiem pakalpojumiem un/vai produktiem, ko salons piedāvā (salona pakalpojumu sniegšanas noteikumus var iegūt atbilstošajā salonā). Katra salona vispārējie atcelšanas un neierašanās gadījumu noteikumi ir pieejami mūsu mājas lapas salona informatīvajā lapā, kā arī rezervējuma veikšanas procesā un rezervējuma apstiprinājuma e-pastā. Lūdzu, ievērojiet, ka noteiktas cenas un īpašos piedāvājumus nav iespējams atcelt vai mainīt. Lūdzu, rūpīgi pārbaudiet pakalpojuma informāciju par šiem noteikumiem pirms rezervējuma veikšanas. Ņemiet vērā, ka rezervējums, kam ir nepieciešama daļēja vai pilna priekšapmaksa, var tikt atcelts (bez iepriekšēja brīdinājuma vai paziņojuma par saistību nepildīšanu), ja attiecīgā (atlikusī) naudas summa pilnībā nevar tikt iekasēta noteiktajā maksājuma datumā, kā tas ir norādīts salona un rezervējuma attiecīgajos apmaksas noteikumos. Novēlots maksājums, nepareizi norādīta banka, debetkartes vai kredītkartes informācija, nederīga kredītkarte vai debetkarte vai nepietiekami līdzekļi ir jūsu pašu risks un atbildība, un jums nav tiesību uz nekādu (neatmaksājamas) priekšapmaksas summas atmaksu, izņemot, ja salons tam piekrīt vai to atļauj pretēji salona priekšapmaksas (apmaksas) un atcelšanas noteikumiem.</p>

<p>Ja vēlaties pārskatīt, mainīt vai atcelt rezervējumu, lūdzu pārskatiet rezervējuma apstiprinājuma e-pastu un sekojiet norādījumiem. Lūdzu, ņemiet vērā, ka par atcelšanu jums var piemērot maksu saskaņā ar salona atcelšanas un (priekš)apmaksas noteikumiem, un jums var nebūt tiesību saņemt atpakaļ ne pilnu, ne daļēji (priekš)apmaksas summu. Mēs iesakām jums pirms rezervējuma veikšanas rūpīgi pārlasīt salona atcelšanas un (priekš)apmaksas noteikumus un atcerēties laicīgi veikt nepieciešamos maksājumus, kā tas ir norādīts attiecīgajā rezervējumā.</p>

<h3 class="heading">7. Tālāka korespondence</h3>
<p>Pabeidzot savu rezervējumu, jūs piekrītat (i) saņemt e-pastu, ko mēs jums varam nosūtīt neilgi pirms pakalpojuma datuma, sniedzot informāciju par jūsu pakalpojumu, kā arī citu informāciju un piedāvājumus (ieskaitot trešo pušu piedāvājumus, ko jūs piekritāt saņemt), kas ir saistīti ar jūsu pakalpojumu, un (ii) e-pastu, ko mēs varam jums nosūtīt neilgi pēc jūsu pakalpojuma datuma, aicinot aizpildīt mūsu viesu atsauksmju anketu. Lūdzu, skatiet mūsu Privātuma un sīkdatņu deklarāciju, lai uzzinātu vairāk par to, kā mēs varam ar jums sazināties.</p>

<h3 class="heading">8. Reitings un viesu atsauksmes</h3>
<p>Parasti salonu reitings mūsu mājas lapā tiek attēlots kā 'iesaka' (vai līdzīgs formulējums) ("parastais reitings"). Jūsu ērtībai mēs piedāvājam arī citus veidus kā salīdzināt salonus. Lūdzu, ņemiet vērā, ka "parasto reitingu" sastāda pilnībā automātiska vērtēšanas sistēma (algoritms), balstoties uz vairākiem kritērijiem.</p>

<p>Aizpildīta viesu atsauksme var tikt ielādēta un izmantota atbilstošās salona informatīvajā lapā mūsu mājas lapā, lai informētu (potenciālos nākotnes) klientus par jūsu viedokli par pakalpojumu (līmeni) un salona kvalitāti, un (b) (pilnībā vai daļēji) izmantota un izvietota tobook.lv mājas lapā pēc mūsu ieskatiem (piemēram, mārketingam, pārdošanas veicināšanai vai mūsu pakalpojumu uzlabošanai), vai tādos sociālo mediju tīklos, ziņojumos, īpašajos piedāvājumos, aplikācijās vai, izmantojot citus kanālus, kam īpašnieks, lietotājs vai kontrolētājs ir tobook.lv  vai mūsu biznesa partneri. Mēs paturam tiesības pielāgot, noraidīt vai dzēst atsauksmes pēc mūsu ieskatiem. Viesu atsauksmes anketa ir pētījuma nolūkiem, tā neietver nekādus (tālākus komerciālus) piedāvājumus, ielūgumus vai citus tamlīdzīgus pamudinājumus.</p>

<h3 class="heading">9. Atbildība</h3>
<p>Tomēr un ciktāl to paredz likums, ne mēs, ne kāds no mūsu amatpersonām, direktoriem, darbiniekiem, pārstāvjiem, filiālēm, saistītiem uzņēmumiem, izplatītājiem, filiāles (izplatītāju) partneriem, licenzētajiem pārstāvjiem, aģentiem vai citiem, kas ir iesaistīti mūsu mājas lapas un tās satura radīšanā, sponsorēšanā, reklamēšanā u.c. nav atbildīgi par (i) sodiem, īpašiem, netiešiem vai izrietošiem zaudējumiem un bojājumiem, ražošanas zudumiem, peļņas zudumiem, apgrozījuma zudumiem, līgumu zudumiem, labās gribas vai reputācijas zudumiem, pretenzijas zudumiem; (ii) jebkādu neprecizitāti salona (aprakstošajā) informācijā (tostarp cenas, pieejamību un reitingiem), kuru tā ir padarījusi pieejamu mūsu mājas lapā; (iii) nodrošinātajiem pakalpojumiem un produktiem, kurus nodrošina salons vai citi biznesa partneri; (iv) jebkādiem (tiešiem, netiešiem, izrietošiem vai soda) bojājumiem, zaudējumiem vai izmaksām, kas ir radušās vai jūs tās esat apmaksājis, sakarā ar aizkavēšanos, savienojuma pārtraukumu vai zudumu, mūsu mājas lapas izmantošanas pārtraukuma vai aizkavēšanās rezultātā; (v) jebkādām (personiskām) traumām, nāves, īpašuma bojājumiem vai citiem (tiešiem, netiešiem, tīšiem, izrietošiem vai soda) zaudējumiem, bojājumiem vai izmaksām, kas radušās, vai arī esat apmaksājis sakarā ar (juridiskiem) aktiem, kļūdām, pārkāpumiem, (bruto) nolaidības, apzinātiem pārkāpumiem, sagrozīšanu, izspiešanu vai stingru atbildību no (pilnībā vai daļēji) salona vai jebkura mūsu biznesa partnera (ieskaitot salona vai biznesa partnera darbiniekus, direktorus, amatpersonas, aģentus, pārstāvjus vai saistītos uzņēmumus), kuru pakalpojumi un produkti (tieši vai netieši) tiek padarīti pieejami, piedāvāti un reklamēti mūsu mājas lapā vai izmantojot mūsu mājas lapu, tostarp jebkādām (arī daļējām) atcelšanām, virsnormas rezervējumiem, streikiem, nepārvaramās varas vai jebkādiem citiem apstākļiem, kas ir ārpus mūsu kontroles.</p>

<p>Neatkarīgi no tā, vai maksu no jums par jūsu pakalpojumu iekasē (vai ir iekasējusi) salons, kurā jūs uzturaties, vai arī uzņēmums tobook.lv pārvalda maksājumu par pakalpojuma cenu, jūs piekrītat un apstiprināt, ka salons jebkurā gadījumā ir atbildīgs par piemērojamo un paredzēto nodokļu iekasēšanu, ieturēšanu, pārskaitīšanu un maksāšanu atbilstošajām nodokļu iestādēm par pilnu pakalpojuma cenu. Tobook.lv nav atbildīgs par piemērojamo un paredzēto nodokļu ieturēšanu, iekasēšanu, pārskaitīšanu un maksāšanu no pakalpojuma cenas atbilstošajām nodokļu iestādēm.</p>

<h3 class="heading">10. Intelektuālā īpašuma tiesības</h3>
<p>Augšupielādējot fotogrāfijas/bildes mūsu sistēmā (piemēram, kā papildinājumu atsauksmēm), Jūs apstiprināt, garantējat un piekrītat tam, ka Jums pieder šo fotogrāfiju/bilžu autortiesības, un Jūs piekrītat tam, ka tobook.lv var izmantot augšupielādētās fotogrāfijas/bildes uzņēmuma (mobilajā) mājas lapā un aplikācijās, (tiešsaistes/bezsaistes) reklamēšanas materiālos un publikācijās, kā arī tur, kur pēc tobook.lv ieskatiem tas būtu piemēroti. Jūs piešķirat tobook.lv turētājam neekskluzīvas, starptautiskas, neatsaucamas, bezierunu un mūžīgas tiesības un licenci izmantot, reproducēt, rādīt, likt reproducēt, izplatīt, izsniegt apakšlicenci, paziņot un padarīt pieejamas fotogrāfijas/bildes tā, kā pēc tobook.lv ieskatiem tas būtu piemēroti. Augšupielādējot šīs fotogrāfijas/bildes, persona, kas augšupielādēja attēlu(-s), uzņemas pilnu juridisku un morālu atbildību par jebkādiem un visiem tiesībpamatotiem prasījumiem no jebkādām trešajām personām (to skaitā salonu īpašniekiem, bet ne tikai) par to, ka tobook.lv publicē un izmanto šīs fotogrāfijas/bildes. Mājas lapai tobook.lv  nepieder, un tas neapstiprina augšupielādētās fotogrāfijas/bildes. Tiek pieņemts, ka personai, kas augšupielādēja fotogrāfijas/attēlus, ir patiesas un likumīgas tiesības izmantot visas fotogrāfijas/attēlus un ka šīs tiesības nav tobook.lv atbildība. Mājas lapa tobook.lv neuzņemas nekādu atbildību un saistības par publicētajām fotogrāfijām/attēliem. Persona, kas augšupielādēja fotogrāfijas, garantē, ka fotogrāfijas/bildes nesatur ne vīrusus, ne “Trojas zirgus”, ne inficētus failus, kā arī tur nav ne pornogrāfiskas, ne prettiesiskas, ne apvainojošas, ne nepieņemamas, ne nepiemērotas informācijas, un neierobežo nekādas trešo pušu (intelektuālā īpašuma tiesības, autortiesības vai privātumu) tiesības. Jebkuras fotogrāfijas/bildes, kas neatbilst iepriekšminētajiem kritērijiem, netiks publicēts, un/vai tobook.lv administrācija to var noņemt/dzēst jebkurā laikā un bez iepriekšēja brīdinājuma.</p>

<p>Tobook.lv, tās piegādātāji un nodrošinātāji, ja vien nav norādīts citādi, ir programmatūras īpašnieki, kas nepieciešama pakalpojumu nodrošināšanai mājas lapā, kā arī satura intelektuālā īpašuma tiesību (tostarp autortiesību) īpašnieki.</p>

<p>Uzņēmums AS DELFI, tobook.lv īpašnieks,  patur ekskluzīvas īpašumtiesības par un uz visām mājas lapas tiesībām, nosaukumu un interesēm (visas intelektuālā īpašuma tiesības) (mājas lapas izskats un sajūta (tostarp infrastruktūra)), kurā ir pieejams pakalpojums (ieskaitot viesu rakstītās atsauksmes). Jums nav tiesību ne pilnībā, ne daļēji kopēt, ievietot hipersaiti un/vai dziļo saiti, publicēt, veicināt, izmantot tirgū, integrēt, lietot, kombinēt vai kā citādi izmantot saturu (ieskaitot jebkurus tulkojumus un viesu atsauksmes) vai uzņēmuma zīmolu bez mūsu iepriekšējas rakstiskas atļaujas. Gadījumā, ja jūs (pilnībā vai daļēji) lietotu vai kombinētu mūsu (tulkoto) saturu (ieskaitot viesu atsauksmes) vai citādi izmantotu jebkādas intelektuālā īpašuma tiesības uz mājas lapu vai jebkādu (tulkoto) saturu vai viesu atsauksmēm, ar šo jūs piešķirat un nododat visas šīs intelektuālā īpašuma tiesības uzņēmumam AS DELFI. Jebkāda nelikumīga izmantošana vai jebkuras iepriekš minētās darbības vai aktivitātes tiks uzskatītas par būtisku mūsu intelektuālā īpašuma tiesību (tostarp autortiesību un datu bāzes tiesību) pārkāpumu ar materiālu atbildību.</p>

<h3 class="heading">11. Dažādi</h3>
<p>Ciktāl to atļauj normatīvie akti, šie nosacījumi un noteikumi un mūsu pakalpojumu nodrošināšana ir pārraudzīta un sastādīta saskaņā ar Latvijas normatīvo aktu prasībām, un jebkāda šo vispārējo noteikumu un nosacījumu pārkāpšanas gadījumā strīds tiek risināts LR tiesā vai Komerctiesību asociācijas šķīrējtiesā (reģistrācijas numurs 40003764832) viena tiesneša tiesas sastāvā latviešu valodā.</p>

<h3 class="heading">12. Par uzņēmumu AS DELFI</h3>
<p>Tiešsaistes skaistumkopšanas salonu pakalpojumu rezervējumu servisu nodrošina uzņēmums AS DELFI, kas ir pakļauts Latvijas likumdošanai. Uzņēmuma birojs atrodas adresē Mūkusalas 41b-9 Rīga, Latvijā. Uzņēmums reģistrācijas numurs ir 40003504352. Mūsu PVN reģistrācijas numurs ir LV40003504352.</p>

</div>
@stop
