---
- name: restart apache2
  shell: apache2ctl graceful

- name: restart mysql
  shell: service mysql restart

- name: update supervisor
  shell: supervisorctl reread

- name: reload supervisor
  shell: supervisorctl reload
