---
- name: create apache log directory
  action: file dest={{ webapps_dir }}/{{ app_name }}/log/apache state=directory

#- name: Copy the code from repository
#  git: repo={{ repository }} dest={{ webapps_dir }}/{{ app_name }}/src accept_hostkey=yes

- name: chmod storage folder
  file: group=www-data owner=www-data recurse=yes path={{ webapps_dir }}/{{ app_name }}/src/app/storage
  tags: templated_settings

- name: chown tmp folder
  file: group=www-data owner=www-data state=directory recurse=yes path={{ webapps_dir }}/{{ app_name }}/src/public/tmp
  tags: templated_settings

- include: sync_settings.yml
