ALTER TABLE `mails` ADD `sendtof` INT NOT NULL DEFAULT '0';
ALTER TABLE `banned_domains` DEFAULT CHARACTER SET utf8;
ALTER TABLE `banned_domains` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `campaigns` DEFAULT CHARACTER SET utf8;
ALTER TABLE `campaigns` CHANGE `description` `description` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `campaigns` CHANGE `categories` `categories` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `categories` DEFAULT CHARACTER SET utf8;
ALTER TABLE `categories` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `categories` CHANGE `description` `description` text CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `categories_subscribers` DEFAULT CHARACTER SET utf8;
ALTER TABLE `configurations` DEFAULT CHARACTER SET utf8;
ALTER TABLE `configurations` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `configurations` CHANGE `description` `description` text CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `configurations` CHANGE `host` `host` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `configurations` CHANGE `username` `username` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `configurations` CHANGE `password` `password` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `configurations` CHANGE `from` `from` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `configurations` CHANGE `reply_to` `reply_to` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `configurations` CHANGE `inbox_host` `inbox_host` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `configurations` CHANGE `inbox_flags` `inbox_flags` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `configurations` CHANGE `mailbox` `mailbox` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `configurations` CHANGE `inbox_username` `inbox_username` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `configurations` CHANGE `inbox_password` `inbox_password` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `forms` DEFAULT CHARACTER SET utf8;
ALTER TABLE `forms` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `forms` CHANGE `description` `description` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `forms` CHANGE `title` `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `forms` CHANGE `content` `content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `forms` CHANGE `selected_categories` `selected_categories` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `forms` CHANGE `thanks_text` `thanks_text` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `forms` CHANGE `style` `style` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `forms` CHANGE `unsubscribe_text` `unsubscribe_text` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `forms` CHANGE `unsubscribe_title` `unsubscribe_title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `forms` CHANGE `thanks_title` `thanks_title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `forms` CHANGE `confirm_mail` `confirm_mail` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `forms` CHANGE `notify_mail` `notify_mail` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `forms` CHANGE `notify_addresse` `notify_addresse` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `forms` CHANGE `confirm_text` `confirm_text` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `forms` CHANGE `confirm_title` `confirm_title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `importtasks` DEFAULT CHARACTER SET utf8;
ALTER TABLE `importtasks` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `importtasks` CHANGE `connection` `connection` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `importtasks` CHANGE `query` `query` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `importtasks` CHANGE `fields` `fields` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `importtasks` CHANGE `categories` `categories` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `importtasks` CHANGE `description` `description` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `importtasks` CHANGE `act` `act` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL  ;
ALTER TABLE `links` DEFAULT CHARACTER SET utf8;
ALTER TABLE `links` CHANGE `url` `url` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `mails` DEFAULT CHARACTER SET utf8;
ALTER TABLE `mails` CHANGE `subject` `subject` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `mails` CHANGE `content_html` `content_html` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `mails` CHANGE `content_text` `content_text` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `mails` CHANGE `final_html` `final_html` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `mails` CHANGE `prepared` `prepared` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci  NOT NULL   DEFAULT '0';
ALTER TABLE `mails_categories` DEFAULT CHARACTER SET utf8;
ALTER TABLE `recipients` DEFAULT CHARACTER SET utf8;
ALTER TABLE `subscribers` DEFAULT CHARACTER SET utf8;
ALTER TABLE `subscribers` CHANGE `first_name` `first_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `subscribers` CHANGE `last_name` `last_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `subscribers` CHANGE `mail_adresse` `mail_adresse` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `subscribers` CHANGE `notes` `notes` text CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `subscribers` CHANGE `unsubscribe_code` `unsubscribe_code` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `templates` DEFAULT CHARACTER SET utf8;
ALTER TABLE `templates` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `templates` CHANGE `content` `content` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `templates` CHANGE `preview` `preview` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `templates` CHANGE `fields` `fields` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `templates` CHANGE `fields_array` `fields_array` longtext CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `users` DEFAULT CHARACTER SET utf8;
ALTER TABLE `users` CHANGE `username` `username` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `users` CHANGE `password` `password` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci  NULL   DEFAULT NULL ;
ALTER TABLE `subscribers` ADD `custom1` VARCHAR( 255 ) NOT NULL ,
ADD `custom2` VARCHAR( 255 ) NOT NULL ,
ADD `custom3` VARCHAR( 255 ) NOT NULL ,
ADD `custom4` VARCHAR( 255 ) NOT NULL;
ALTER TABLE `recipients` ADD `country` VARCHAR( 255 ) NOT NULL ;