---
- name: add redis repo
  apt_repository: repo='ppa:chris-lea/redis-server'

- name: ensure apt cache is up to date
  action: apt update_cache=yes

- name: install common packages needed for development
  action: apt pkg={{ item }} state=installed
  with_items:
    - apache2
    - git
    - curl
    - libcurl3
    - libcurl3-dev
    - php5-curl
    - php5-mcrypt
    - sendmail
    - openjdk-7-jre-headless
    - redis-server

- name: remove default apache site
  action: file path=/etc/apache2/sites-available/000-default.conf state=absent

- name: remove default apache site
  action: file path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: start apache2 service and have it run during system startup
  action: service name=apache2 state=started enabled=yes

- name: download composer
  shell: curl -sS https://getcomposer.org/installer | php

- name: enable composer
  shell: mv composer.phar /usr/local/bin/composer

- name: download eslasticsearch package
  get_url: url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.4.deb dest=/tmp/elasticsearch.deb

- name: install elasticsearch
  apt: deb=/tmp/elasticsearch.deb state=installed

- name: start elasticsearch service
  action: service name=elasticsearch state=started enabled=yes

- name: start redis
  action: service name=redis-server state=started enabled=yes
